# Generated by Django 5.2 on 2025-04-11 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0003_user_otp_user_otp_expiry_alter_user_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionnaireSubmission",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="questionnaire_submission",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("is_complete", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "identifier",
                    models.SlugField(
                        help_text="Unique identifier for this question (e.g., 'has_idea', 'problem')",
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        help_text="The wording of the question (questionText)"
                    ),
                ),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("singleSelect", "Single Select Radio"),
                            ("multiSelect", "Multiple Select Checkbox"),
                            ("descriptive", "Short Answer / Descriptive Text"),
                            ("fileUpload", "File Upload"),
                            ("yesNo", "Yes/No Choice"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Section title for grouping (e.g., 'Your Idea & Current Stage').",
                        max_length=100,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True,
                        default=0,
                        help_text="Order within the questionnaire/section.",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Only active questions will be fetched.",
                    ),
                ),
                (
                    "options",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="JSON list of strings for choice options.",
                        null=True,
                    ),
                ),
                ("hint_text", models.CharField(blank=True, max_length=255, null=True)),
                ("max_characters", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "depends_on_answer",
                    models.CharField(
                        blank=True,
                        help_text="The 'value' (answer text) from the parent question that triggers this one.",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "depends_on_question",
                    models.ForeignKey(
                        blank=True,
                        help_text="The 'key' (identifier) of the question this one depends on.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dependent_questions",
                        to="questionnaire.question",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "answer_value",
                    models.JSONField(
                        blank=True,
                        help_text="Stores text answer, single choice, or list of multi-choices.",
                        null=True,
                    ),
                ),
                (
                    "answer_file",
                    models.FileField(
                        blank=True, null=True, upload_to="user_answers/files/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="answers",
                        to="questionnaire.question",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="questionnaire.questionnairesubmission",
                    ),
                ),
            ],
            options={
                "ordering": ["question__order"],
                "unique_together": {("submission", "question")},
            },
        ),
    ]
